name: Terraform EC2 Deployment

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy resources'
        required: true
        default: 'true'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: AWS
    defaults:
      run:
        working-directory: ./code/EC2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Secrets Availability
      run: |
        echo "Check if secrets are available (without revealing values):"
        if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          echo "AWS_ACCESS_KEY_ID is set and not empty"
        else
          echo "AWS_ACCESS_KEY_ID is NOT set or is empty"
        fi

        if [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
          echo "AWS_SECRET_ACCESS_KEY is set and not empty"
        else
          echo "AWS_SECRET_ACCESS_KEY is NOT set or is empty"
        fi

        echo "Using AWS region: us-east-2"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Verify AWS CLI
      run: aws sts get-caller-identity

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      if: ${{ github.event.inputs.destroy == 'true' }}
      run: |
        echo "DESTROYING ALL RESOURCES!"
        terraform destroy -auto-approve
      timeout-minutes: 15
